[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = ["dotnet restore", "dotnet build --configuration Release"]

[phases.deploy]
cmds = ["dotnet PhonebookAPI.dll"]

[start]
cmd = "dotnet PhonebookAPI.dll"
